services:
  web-bot-blahaj:
    build: .
    container_name: web-bot-blahaj
    ports:
      - "80:80"
    volumes:
      - .:/usr/local/apache2/htdocs/
    restart: unless-stopped
    mem_limit: 100m
